"""customer_id not null

Revision ID: 896a17672ae0
Revises: 629914acf7f5
Create Date: 2024-11-19 15:10:37.736702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896a17672ae0'
down_revision = '629914acf7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
